language: php

php:
  - 5.5
  - 5.6

before_script:
  - composer install -n --ignore-platform-reqs
  - composer require codeclimate/php-test-reporter:dev-master@dev --ignore-platform-reqs

script: ./vendor/bin/phpunit # --coverage-clover build/logs/clover.xml

