language: php

php:
  - 5.5
  - 5.6

before_script:
  - sudo apt-get update
  - sudo apt-get install libv8-dev
  - echo '' | pecl install v8js-0.1.3
  - composer install -n

script: ./vendor/bin/phpunit # --coverage-clover build/logs/clover.xml

