language: php

php:
  - 5.5
  - 5.6

before_script:
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - export PATH=`pwd`/depot_tools:"$PATH"
  - fetch v8
  - cd v8
  - git checkout 4.9.99
  - gclient sync
  - make native library=shared snapshot=off -j8
  - sudo mkdir -p /usr/lib /usr/include
  - sudo cp out/native/lib.target/lib*.so /usr/lib/
  - sudo cp -R include/* /usr/include
  - echo -e "create /usr/lib/libv8_libplatform.a\naddlib out/native/obj.target/tools/gyp/libv8_libplatform.a\nsave\nend" | sudo ar -M
  #- echo "\n" | pecl install v8js

  - cd /tmp
  - git clone https://github.com/preillyme/v8js.git
  - cd v8js
  - phpize
  - ./configure --with-v8js=/usr
  - make
  - make test
  - sudo make install

  - cd $TRAVIS_BUILD_DIR
  - composer install -n

script: ./vendor/bin/phpunit # --coverage-clover build/logs/clover.xml

