language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer install -n --ignore-platform-reqs
  - composer require codeclimate/php-test-reporter:dev-master@dev --ignore-platform-reqs

script: ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - ./vendor/bin/test-reporter

addons:
  code_climate:
    repo_token: aa0ad43580b580164adf80c8aee4d47e6e313b47db549e5ecb6abd62447b412c
